// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcCore_DbFirstApproach.Models;

#nullable disable

namespace MvcCore_DbFirstApproach.Migrations
{
    [DbContext(typeof(LpuDbContext))]
    [Migration("20260309051814_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MvcCore_DbFirstApproach.Models.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptId"));

                    b.Property<string>("DeptName")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("DeptId")
                        .HasName("PK__Departme__014881AEA0E15FD2");

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("MvcCore_DbFirstApproach.Models.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpId"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("DeptId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("JoinDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<int?>("Salary")
                        .HasColumnType("int");

                    b.HasKey("EmpId")
                        .HasName("PK__Employee__AF2DBB99EBD8BA59");

                    b.HasIndex("DeptId");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("MvcCore_DbFirstApproach.Models.Product", b =>
                {
                    b.Property<int>("ProdId")
                        .HasColumnType("int")
                        .HasColumnName("ProdID");

                    b.Property<string>("Category")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProdId")
                        .HasName("PK__Product__042785C5F7DBFCD9");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("MvcCore_DbFirstApproach.Models.StudentInfo", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StudentAddress")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("StudentName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("StudentId")
                        .HasName("PK__StudentI__32C52A79EF4C5831");

                    b.ToTable("StudentInfo", (string)null);
                });

            modelBuilder.Entity("MvcCore_DbFirstApproach.Models.Employee", b =>
                {
                    b.HasOne("MvcCore_DbFirstApproach.Models.Department", "Dept")
                        .WithMany("Employees")
                        .HasForeignKey("DeptId")
                        .HasConstraintName("FK__Employee__DeptId__4CA06362");

                    b.Navigation("Dept");
                });

            modelBuilder.Entity("MvcCore_DbFirstApproach.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
